countries = [
    ("", "اختر البلد"),
    ("Afghanistan", "Afghanistan - أفغانستان"),
    ("Albania", "Albania - ألبانيا"),
    ("Algeria", "Algeria - الجزائر"),
    ("Andorra", "Andorra - أندورا"),
    ("Angola", "Angola - أنغولا"),
    ("Argentina", "Argentina - الأرجنتين"),
    ("Armenia", "Armenia - أرمينيا"),
    ("Australia", "Australia - أستراليا"),
    ("Austria", "Austria - النمسا"),
    ("Azerbaijan", "Azerbaijan - أذربيجان"),
    ("Bahamas", "Bahamas - جزر البهاما"),
    ("Bahrain", "Bahrain - البحرين"),
    ("Bangladesh", "Bangladesh - بنغلاديش"),
    ("Barbados", "Barbados - باربادوس"),
    ("Belarus", "Belarus - بيلاروسيا"),
    ("Belgium", "Belgium - بلجيكا"),
    ("Belize", "Belize - بليز"),
    ("Benin", "Benin - بنين"),
    ("Bhutan", "Bhutan - بوتان"),
    ("Bolivia", "Bolivia - بوليفيا"),
    ("Bosnia and Herzegovina", "Bosnia and Herzegovina - البوسنة والهرسك"),
    ("Botswana", "Botswana - بوتسوانا"),
    ("Brazil", "Brazil - البرازيل"),
    ("Brunei", "Brunei - بروناي"),
    ("Bulgaria", "Bulgaria - بلغاريا"),
    ("Burkina Faso", "Burkina Faso - بوركينا فاسو"),
    ("Burundi", "Burundi - بوروندي"),
    ("Cabo Verde", "Cabo Verde - الرأس الأخضر"),
    ("Cambodia", "Cambodia - كمبوديا"),
    ("Cameroon", "Cameroon - الكاميرون"),
    ("Canada", "Canada - كندا"),
    ("Central African Republic", "Central African Republic - جمهورية أفريقيا الوسطى"),
    ("Chad", "Chad - تشاد"),
    ("Chile", "Chile - تشيلي"),
    ("China", "China - الصين"),
    ("Colombia", "Colombia - كولومبيا"),
    ("Comoros", "Comoros - جزر القمر"),
    ("Congo, Democratic Republic of the", "Congo, Democratic Republic of the - جمهورية الكونغو الديمقراطية"),
    ("Congo, Republic of the", "Congo, Republic of the - جمهورية الكونغو"),
    ("Costa Rica", "Costa Rica - كوستاريكا"),
    ("Croatia", "Croatia - كرواتيا"),
    ("Cuba", "Cuba - كوبا"),
    ("Cyprus", "Cyprus - قبرص"),
    ("Czech Republic", "Czech Republic - جمهورية التشيك"),
    ("Denmark", "Denmark - الدنمارك"),
    ("Djibouti", "Djibouti - جيبوتي"),
    ("Dominica", "Dominica - دومينيكا"),
    ("Dominican Republic", "Dominican Republic - جمهورية الدومينيكان"),
    ("Ecuador", "Ecuador - الإكوادور"),
    ("Egypt", "Egypt - مصر"),
    ("El Salvador", "El Salvador - السلفادور"),
    ("Equatorial Guinea", "Equatorial Guinea - غينيا الاستوائية"),
    ("Eritrea", "Eritrea - إريتريا"),
    ("Estonia", "Estonia - إستونيا"),
    ("Eswatini", "Eswatini - إسواتيني"),
    ("Ethiopia", "Ethiopia - إثيوبيا"),
    ("Fiji", "Fiji - فيجي"),
    ("Finland", "Finland - فنلندا"),
]